disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
line_length:
  warning: 180
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
